### PR TITLE
Linked the apijey.js file to the other JS files by adding a script li…

### PR DESCRIPTION
**Pull request by Antimio**
…nk to it on the html files

### CODE REVIEW

**Review by kamilawroblewska — COMMENTED** [review]
looks good :)

**Review by rhipsime — CHANGES_REQUESTED** [review]
Please make sure you have done the git origin. There is a merge 
Screenshot 2024-02-06 at 18 45 31
conflict.

**Review by kamilawroblewska — APPROVED** [review]
now fine

**Review by kamilawroblewska — APPROVED** [review]
resolved

**Review by rhipsime — COMMENTED** [review]
I think you need to resolve the merge conflict

**Review by rhipsime — APPROVED** [review]

**Pull request merged**
